<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TypeScriptTarget>ES2021</TypeScriptTarget>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Aspose.Words" Version="26.2.0" />
	  <PackageReference Include="EFCore.BulkExtensions" Version="9.0.2" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.9.3">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Stimulsoft.Reports.Engine.Blazor" Version="2025.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.14" />
  </ItemGroup>
	<ItemGroup>
		<Content Include="Help\**" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Accounting\Accounting.Model\Accounting.Model.csproj" />
    <ProjectReference Include="..\Accounting\Accounting.Service\Accounting.Service.csproj" />
    <ProjectReference Include="..\Accounting\Accounting.Web\Accounting.Web.csproj" />
    <ProjectReference Include="..\Caspian.common\Caspian.common.csproj" />
    <ProjectReference Include="..\Demo\Demo.Model\Demo.Model.csproj" />
    <ProjectReference Include="..\Demo\Demo.Service\Demo.Service.csproj" />
    <ProjectReference Include="..\Demo\Demo.Web\Demo.Web.csproj" />
    <ProjectReference Include="..\Engine\Engine.Model\Engine.Model.csproj" />
    <ProjectReference Include="..\Engine\Engine.Service\Engine.Service.csproj" />
    <ProjectReference Include="..\Engine\Engine.Web\Engine.Web.csproj" />
    <ProjectReference Include="..\Investment\Investment.Service\Investment.Service.csproj" />
    <ProjectReference Include="..\Investment\Investment.Web\Investment.Web.csproj" />
    <ProjectReference Include="..\Marketing\Marketing.Model\Marketing.Model.csproj" />
    <ProjectReference Include="..\Marketing\Marketing.Service\Marketing.Service.csproj" />
    <ProjectReference Include="..\Marketing\Marketing.Web\Marketing.Web.csproj" />
    <ProjectReference Include="..\Procurement\Procurement.Model\Procurement.Model.csproj" />
    <ProjectReference Include="..\Procurement\Procurement.Service\Procurement.Service.csproj" />
    <ProjectReference Include="..\Procurement\Procurement.Service\Procurement.Web\Procurement.Web.csproj" />
    <ProjectReference Include="..\Report\Common.Client\Common.Client.csproj" />
    <ProjectReference Include="..\Report\ReportGenerator.Client\ReportGenerator.Client.csproj" />
    <ProjectReference Include="..\Report\UIComponent.Client\UIComponent.Client.csproj" />
    <ProjectReference Include="..\UIComponent\UIComponent.csproj" />
    <ProjectReference Include="..\warehouse\Warehouse.Model\Warehouse.Model.csproj" />
    <ProjectReference Include="..\warehouse\Warehouse.Service\Warehouse.Service.csproj" />
    <ProjectReference Include="..\warehouse\Warehouse.Web\Warehouse.Web.csproj" />
  </ItemGroup>
	<ItemGroup>
		<_CustomFiles Include="$(MSBuildProjectDirectory)/../Demo/Demo.web/Help/**" />
		<Compile Remove="Errors\**" />
		<Compile Remove="obj\**" />
		<Compile Remove="PersistKey\**" />
		<Content Remove="Errors\**" />
		<Content Remove="obj\**" />
		<Content Remove="PersistKey\**" />
		<EmbeddedResource Remove="Errors\**" />
		<EmbeddedResource Remove="obj\**" />
		<EmbeddedResource Remove="PersistKey\**" />
		<None Remove="Errors\**" />
		<None Remove="obj\**" />
		<None Remove="PersistKey\**" />
		<TypeScriptCompile Remove="Errors\**" />
		<TypeScriptCompile Remove="obj\**" />
		<TypeScriptCompile Remove="PersistKey\**" />
		<Content Remove="wwwroot\Report\ReportGenerator.ts" />
		<DotNetPublishFiles Include="@(_CustomFiles)">
			<DestinationRelativePath>Help/%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
		</DotNetPublishFiles>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Languages\" />
	</ItemGroup>
	<ItemGroup>
	  <TypeScriptCompile Include="wwwroot\Report\ReportGenerator.ts" />
	</ItemGroup>
</Project>
