<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Caspian.common\Caspian.common.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Model\Engine.Model.csproj" />
  </ItemGroup>

</Project>
