<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Pages\Lookups\**" />
    <Compile Remove="wwwroot\**" />
    <Content Remove="Pages\Lookups\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="Pages\Lookups\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="Pages\Lookups\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Caspian.common\Caspian.common.csproj" />
    <ProjectReference Include="..\..\Common.Component\Common.Component.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Model\Engine.Model.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Service\Engine.Service.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Web\Engine.Web.csproj" />
    <ProjectReference Include="..\..\UIComponent\UIComponent.csproj" />
    <ProjectReference Include="..\Warehouse.Model\Warehouse.Model.csproj" />
    <ProjectReference Include="..\Warehouse.Service\Warehouse.Service.csproj" />
  </ItemGroup>

</Project>
