// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warehouse.Model;

#nullable disable

namespace Warehouse.Model.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260327222708_V29")]
    partial class V29
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Model.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("CostCenters", "acc", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("LineNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<short>("RepetitionTimes")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceCodeFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SubSystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionsData", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExceptionDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionDataId");

                    b.HasIndex("UserId");

                    b.ToTable("ExceptionDetails", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDropped")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<bool>("ShowOnMenu")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<byte>("SubsystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("Menus", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuAccessibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("MenusAccessibility", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconFont")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<byte>("SubsystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Caspian.Engine.Model.UserMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersMembership", "cmn", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Warehouse.Model.BarcodePattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BarcodePatterns", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Branches", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BarcodePatternId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("GoodsNature")
                        .HasColumnType("tinyint");

                    b.Property<byte>("GoodsType")
                        .HasColumnType("tinyint");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductClassId")
                        .HasColumnType("int");

                    b.Property<byte?>("ReservationLevel")
                        .HasColumnType("tinyint");

                    b.Property<bool>("ReserveBaseOnControl")
                        .HasColumnType("bit");

                    b.Property<bool>("SuspendedInIncoming")
                        .HasColumnType("bit");

                    b.Property<bool>("SuspendedInOutcoming")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BarcodePatternId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("ProductClassId");

                    b.ToTable("Goods", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.GoodsPlacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("StockRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StockRoomId");

                    b.ToTable("GoodsPlacements", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.GoodsProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("FixLength")
                        .HasColumnType("bit");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaximumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("MinimumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumberDigit")
                        .HasColumnType("int");

                    b.Property<byte>("PropertyType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("GoodsProperties", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.KeepCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tell")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("LocationId");

                    b.ToTable("KeepCenters", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("LocationType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.MaterialLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<int>("StockroomId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("StockroomId");

                    b.ToTable("MaterialLocations", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MeasurementDimension")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnits", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.ProductClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("PricingMethod")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("ProductClasses", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.PropertyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsPropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsPropertyId");

                    b.ToTable("PropertiesList", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.PurchaseRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<byte>("CostCenterType")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IssuerKeepCenterId")
                        .HasColumnType("int");

                    b.Property<int?>("IssuerStockRoomId")
                        .HasColumnType("int");

                    b.Property<bool>("Loadable")
                        .HasColumnType("bit");

                    b.Property<string>("No")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReceiverKeepCenterId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverStockRoomId")
                        .HasColumnType("int");

                    b.Property<byte>("ReferenceDocumentType")
                        .HasColumnType("tinyint");

                    b.Property<int>("RequisitionerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StockRoomDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("IssuerKeepCenterId");

                    b.HasIndex("IssuerStockRoomId");

                    b.HasIndex("ReceiverKeepCenterId");

                    b.HasIndex("ReceiverStockRoomId");

                    b.HasIndex("RequisitionerId");

                    b.ToTable("PurchaseRequests", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("KeepCenterId")
                        .HasColumnType("int");

                    b.Property<byte>("OtherPartyType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ReservationBasis")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReservationNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ReservationType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("StockRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("KeepCenterId");

                    b.HasIndex("StockRoomId");

                    b.ToTable("Reservations", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.StandardChangeUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MainUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OtherUnitId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("MainUnitId");

                    b.HasIndex("OtherUnitId");

                    b.ToTable("StandardChangeUnits", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.StockRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KeepCenterId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<bool>("MemberInManyParts")
                        .HasColumnType("bit");

                    b.Property<bool>("MemberOfMiddlePart")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("KeepCenterId");

                    b.HasIndex("ManagerId");

                    b.ToTable("StockRooms", "wh");
                });

            modelBuilder.Entity("Warehouse.Model.SubstituteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DuplicateRelation")
                        .HasColumnType("bit");

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.Property<int>("SubstituteGoodsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("SubstituteGoodsId");

                    b.ToTable("SubstituteProducts", "wh");
                });

            modelBuilder.Entity("Accounting.Model.CostCenter", b =>
                {
                    b.HasOne("Accounting.Model.CostCenter", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionDetail", b =>
                {
                    b.HasOne("Caspian.Engine.Model.ExceptionData", "ExceptionData")
                        .WithMany("Details")
                        .HasForeignKey("ExceptionDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("ExceptionDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExceptionData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.HasOne("Caspian.Engine.Model.MenuCategory", "MenuCategory")
                        .WithMany("Menus")
                        .HasForeignKey("MenuCategoryId");

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuAccessibility", b =>
                {
                    b.HasOne("Caspian.Engine.Model.Menu", "Menu")
                        .WithMany("Accessibilities")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.Role", "Role")
                        .WithMany("MenuAccessibilities")
                        .HasForeignKey("RoleId");

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("Accessibilities")
                        .HasForeignKey("UserId");

                    b.Navigation("Menu");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caspian.Engine.Model.UserMembership", b =>
                {
                    b.HasOne("Caspian.Engine.Model.Role", "Role")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warehouse.Model.Goods", b =>
                {
                    b.HasOne("Warehouse.Model.BarcodePattern", "BarcodePattern")
                        .WithMany("Goods")
                        .HasForeignKey("BarcodePatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Goods")
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.ProductClass", "ProductClass")
                        .WithMany("Goods")
                        .HasForeignKey("ProductClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BarcodePattern");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("ProductClass");
                });

            modelBuilder.Entity("Warehouse.Model.GoodsPlacement", b =>
                {
                    b.HasOne("Warehouse.Model.Goods", "Goods")
                        .WithMany("GoodsPlacements")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.MaterialLocation", "Location")
                        .WithMany("GoodsPlacements")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.StockRoom", "StockRoom")
                        .WithMany("GoodsPlacements")
                        .HasForeignKey("StockRoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Goods");

                    b.Navigation("Location");

                    b.Navigation("StockRoom");
                });

            modelBuilder.Entity("Warehouse.Model.KeepCenter", b =>
                {
                    b.HasOne("Warehouse.Model.Branch", "Branch")
                        .WithMany("KeepCenters")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.Location", "Location")
                        .WithMany("KeepCenters")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Warehouse.Model.Location", b =>
                {
                    b.HasOne("Warehouse.Model.Location", "ParentLocation")
                        .WithMany("Locations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("Warehouse.Model.MaterialLocation", b =>
                {
                    b.HasOne("Warehouse.Model.MaterialLocation", "ParentLocation")
                        .WithMany("Locations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.StockRoom", "StockRoom")
                        .WithMany("MaterialAddresses")
                        .HasForeignKey("StockroomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentLocation");

                    b.Navigation("StockRoom");
                });

            modelBuilder.Entity("Warehouse.Model.PropertyList", b =>
                {
                    b.HasOne("Warehouse.Model.GoodsProperties", "GoodsProperty")
                        .WithMany("Properties")
                        .HasForeignKey("GoodsPropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GoodsProperty");
                });

            modelBuilder.Entity("Warehouse.Model.PurchaseRequest", b =>
                {
                    b.HasOne("Accounting.Model.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.KeepCenter", "IssuerKeepCenter")
                        .WithMany("PurchaseRequestsIssuer")
                        .HasForeignKey("IssuerKeepCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.StockRoom", "IssuerStockRoom")
                        .WithMany("PurchaseRequestsIssuer")
                        .HasForeignKey("IssuerStockRoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.KeepCenter", "ReceiverKeepCenter")
                        .WithMany("PurchaseRequestsReceiver")
                        .HasForeignKey("ReceiverKeepCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.StockRoom", "ReceiverStockRoom")
                        .WithMany("PurchaseRequestsReceiver")
                        .HasForeignKey("ReceiverStockRoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.Model.User", "Requisitioner")
                        .WithMany()
                        .HasForeignKey("RequisitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostCenter");

                    b.Navigation("IssuerKeepCenter");

                    b.Navigation("IssuerStockRoom");

                    b.Navigation("ReceiverKeepCenter");

                    b.Navigation("ReceiverStockRoom");

                    b.Navigation("Requisitioner");
                });

            modelBuilder.Entity("Warehouse.Model.Reservation", b =>
                {
                    b.HasOne("Accounting.Model.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Warehouse.Model.KeepCenter", "KeepCenter")
                        .WithMany("Reservations")
                        .HasForeignKey("KeepCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.StockRoom", "StockRoom")
                        .WithMany("Reservations")
                        .HasForeignKey("StockRoomId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CostCenter");

                    b.Navigation("KeepCenter");

                    b.Navigation("StockRoom");
                });

            modelBuilder.Entity("Warehouse.Model.StandardChangeUnit", b =>
                {
                    b.HasOne("Warehouse.Model.MeasurementUnit", "MainUnit")
                        .WithMany("MainUnits")
                        .HasForeignKey("MainUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.MeasurementUnit", "OtherUnit")
                        .WithMany("OtherUnits")
                        .HasForeignKey("OtherUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MainUnit");

                    b.Navigation("OtherUnit");
                });

            modelBuilder.Entity("Warehouse.Model.StockRoom", b =>
                {
                    b.HasOne("Warehouse.Model.Branch", "Branch")
                        .WithMany("Stocks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.KeepCenter", "KeepCenter")
                        .WithMany("Stocks")
                        .HasForeignKey("KeepCenterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Branch");

                    b.Navigation("KeepCenter");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Warehouse.Model.SubstituteProduct", b =>
                {
                    b.HasOne("Warehouse.Model.Goods", "Goods")
                        .WithMany("Substitutes")
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Warehouse.Model.Goods", "SubstituteGoods")
                        .WithMany("OtherSubstitutes")
                        .HasForeignKey("SubstituteGoodsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Goods");

                    b.Navigation("SubstituteGoods");
                });

            modelBuilder.Entity("Accounting.Model.CostCenter", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionData", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.Navigation("Accessibilities");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuCategory", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Role", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MenuAccessibilities");
                });

            modelBuilder.Entity("Caspian.Engine.Model.User", b =>
                {
                    b.Navigation("Accessibilities");

                    b.Navigation("ExceptionDetails");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Warehouse.Model.BarcodePattern", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("Warehouse.Model.Branch", b =>
                {
                    b.Navigation("KeepCenters");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Warehouse.Model.Goods", b =>
                {
                    b.Navigation("GoodsPlacements");

                    b.Navigation("OtherSubstitutes");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("Warehouse.Model.GoodsProperties", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("Warehouse.Model.KeepCenter", b =>
                {
                    b.Navigation("PurchaseRequestsIssuer");

                    b.Navigation("PurchaseRequestsReceiver");

                    b.Navigation("Reservations");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Warehouse.Model.Location", b =>
                {
                    b.Navigation("KeepCenters");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Warehouse.Model.MaterialLocation", b =>
                {
                    b.Navigation("GoodsPlacements");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Warehouse.Model.MeasurementUnit", b =>
                {
                    b.Navigation("Goods");

                    b.Navigation("MainUnits");

                    b.Navigation("OtherUnits");
                });

            modelBuilder.Entity("Warehouse.Model.ProductClass", b =>
                {
                    b.Navigation("Goods");
                });

            modelBuilder.Entity("Warehouse.Model.StockRoom", b =>
                {
                    b.Navigation("GoodsPlacements");

                    b.Navigation("MaterialAddresses");

                    b.Navigation("PurchaseRequestsIssuer");

                    b.Navigation("PurchaseRequestsReceiver");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
