// <auto-generated />
using System;
using Caspian.Engine.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Engine.Model.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260510154349_V4")]
    partial class V4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Caspian.Engine.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActivityType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("ActorType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("EventTriggerType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("GatewayType")
                        .HasColumnType("tinyint");

                    b.Property<double>("Left")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceCodeFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("TaskType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Top")
                        .HasPrecision(10, 2)
                        .HasColumnType("float(10)");

                    b.Property<int?>("WorkflowFormId")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowFormId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("Activities", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.BlazorControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConditionExpression")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ControlType")
                        .HasColumnType("tinyint");

                    b.Property<string>("CustomeFieldName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DataModelFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("Height")
                        .HasColumnType("tinyint");

                    b.Property<int?>("LookupTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("MultiLine")
                        .HasColumnType("bit");

                    b.Property<string>("OnChange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TextExpression")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataModelFieldId");

                    b.HasIndex("LookupTypeId");

                    b.ToTable("BlazorControls", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.DataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkflowGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowGroupId");

                    b.ToTable("DataModels", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.DataModelField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DataModelId")
                        .HasColumnType("int");

                    b.Property<string>("EntityFullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("FieldType")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDetails")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DataModelId");

                    b.HasIndex("EntityTypeId");

                    b.ToTable("DataModelFields", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.DataModelOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("DataModelOptions", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.DataParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ParameterType")
                        .HasColumnType("tinyint");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ResultParameterId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("DataParameters", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Namespace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Subsystem")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("ValidationType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("EntityTypes", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlColumn", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Hidden")
                        .HasColumnType("bit");

                    b.Property<int?>("InnerRowId")
                        .HasColumnType("int");

                    b.Property<int?>("RowId")
                        .HasColumnType("int");

                    b.Property<byte?>("Span")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("InnerRowId");

                    b.HasIndex("RowId");

                    b.ToTable("HtmlColumns", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Span")
                        .HasColumnType("tinyint");

                    b.Property<int>("WorkflowFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowFormId");

                    b.ToTable("HtmlRows", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.InnerRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HtmlColumnId")
                        .HasColumnType("int");

                    b.Property<byte>("Span")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("HtmlColumnId");

                    b.ToTable("InnerRows", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.LookupType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LookupTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LookupTypes", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.AggregateReportGroupParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("AggregateFunctionType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("AggregateParameterType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Allis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentParameterId");

                    b.HasIndex("ReportGroupId");

                    b.ToTable("AggregateReportGroupsParameter", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.AggregateReportParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AggregateReportGroupParameterId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AggregateReportGroupParameterId");

                    b.HasIndex("ReportId");

                    b.ToTable("AggregateReportsParameters", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.CaspianFont", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Fonts", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("LineNumber")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(2)
                        .HasColumnType("datetime2");

                    b.Property<short>("RepetitionTimes")
                        .HasColumnType("smallint");

                    b.Property<string>("SourceCodeFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("SubSystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionsData", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExceptionDataId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(2)
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExceptionDataId");

                    b.HasIndex("UserId");

                    b.ToTable("ExceptionDetails", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDropped")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<bool>("ShowOnMenu")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<byte>("SubsystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("URL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("Menus", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuAccessibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("MenusAccessibility", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconFont")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<byte>("SubsystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MenuCategories", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.PersianDateTable", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DayOfPersianWeek")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("PersianDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Date");

                    b.ToTable("PersianDatesTable", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descript")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FilteringFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrintFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportGroupId")
                        .HasColumnType("int");

                    b.Property<byte>("ReportType")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SubReportLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReportGroupId");

                    b.ToTable("Reports", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FaTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int?>("Left")
                        .HasColumnType("int");

                    b.Property<int>("TabPanelId")
                        .HasColumnType("int");

                    b.Property<int?>("Top")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TabPanelId");

                    b.ToTable("ReportControls", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descript")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Disable")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameSpace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("SubSystem")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ReportGroups", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportGroupParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsKey")
                        .HasColumnType("bit");

                    b.Property<string>("PropertyPath")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReportGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportGroupId");

                    b.ToTable("ReportGroupsParameters", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("CompositionMethodType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("DataLevel")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReportGroupParameterId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportGroupParameterId");

                    b.HasIndex("ReportId");

                    b.HasIndex("RuleId");

                    b.ToTable("ReportParams", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.TabPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("TabPanels", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComputedColumnSql("[FName] + ' ' + [LName]");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LoginDate")
                        .HasPrecision(2)
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsersLogins", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.UserMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersMembership", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.NodeConnector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<bool>("CheckValidation")
                        .HasColumnType("bit");

                    b.Property<byte?>("CompareType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("PortType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ToActivityId")
                        .HasColumnType("int");

                    b.Property<byte>("ToPortType")
                        .HasColumnType("tinyint");

                    b.Property<decimal?>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ToActivityId");

                    b.ToTable("Connectors", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descript")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EnumTypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("FormRule")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<byte>("ResultType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Rules", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.TaskOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLaste")
                        .HasColumnType("bit");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ConnectorId");

                    b.ToTable("TaskOperations", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("ConstValueType")
                        .HasColumnType("tinyint");

                    b.Property<string>("EnTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FaTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RuleId")
                        .HasColumnType("int");

                    b.Property<int?>("RuleIdValue")
                        .HasColumnType("int");

                    b.Property<byte>("TokenType")
                        .HasColumnType("tinyint");

                    b.Property<string>("constValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("parameterType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("RuleIdValue");

                    b.ToTable("Tokens", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DataModelId")
                        .HasColumnType("int");

                    b.Property<string>("Descript")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkflowGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataModelId");

                    b.HasIndex("WorkflowGroupId");

                    b.ToTable("Workflows", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.WorkflowForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ColumnCount")
                        .HasColumnType("tinyint");

                    b.Property<int>("DataModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkflowGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataModelId");

                    b.HasIndex("WorkflowGroupId");

                    b.ToTable("WorkflowsForms", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.WorkflowGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("SubsystemKind")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WorkflowGroups", "cmn");
                });

            modelBuilder.Entity("Caspian.Engine.Activity", b =>
                {
                    b.HasOne("Caspian.Engine.WorkflowForm", "WorkflowForm")
                        .WithMany("Activities")
                        .HasForeignKey("WorkflowFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.Workflow", "Workflow")
                        .WithMany("Activities")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workflow");

                    b.Navigation("WorkflowForm");
                });

            modelBuilder.Entity("Caspian.Engine.BlazorControl", b =>
                {
                    b.HasOne("Caspian.Engine.DataModelField", "DataModelField")
                        .WithMany("BlazorControls")
                        .HasForeignKey("DataModelFieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.LookupType", "LookupType")
                        .WithMany("BlazorControls")
                        .HasForeignKey("LookupTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DataModelField");

                    b.Navigation("LookupType");
                });

            modelBuilder.Entity("Caspian.Engine.DataModel", b =>
                {
                    b.HasOne("Caspian.Engine.WorkflowGroup", "WorkflowGroup")
                        .WithMany("DataModels")
                        .HasForeignKey("WorkflowGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WorkflowGroup");
                });

            modelBuilder.Entity("Caspian.Engine.DataModelField", b =>
                {
                    b.HasOne("Caspian.Engine.DataModel", "DataModel")
                        .WithMany("Fields")
                        .HasForeignKey("DataModelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.EntityType", "EntityType")
                        .WithMany("DataModelFields")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DataModel");

                    b.Navigation("EntityType");
                });

            modelBuilder.Entity("Caspian.Engine.DataModelOption", b =>
                {
                    b.HasOne("Caspian.Engine.DataModelField", "Field")
                        .WithMany("DataModelOptions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Caspian.Engine.DataParameter", b =>
                {
                    b.HasOne("Caspian.Engine.Rule", "Rule")
                        .WithMany("DataParameters")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlColumn", b =>
                {
                    b.HasOne("Caspian.Engine.BlazorControl", "Component")
                        .WithOne("HtmlColumn")
                        .HasForeignKey("Caspian.Engine.HtmlColumn", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Caspian.Engine.InnerRow", "InnerRow")
                        .WithMany("HtmlColumns")
                        .HasForeignKey("InnerRowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.HtmlRow", "Row")
                        .WithMany("Columns")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Component");

                    b.Navigation("InnerRow");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlRow", b =>
                {
                    b.HasOne("Caspian.Engine.WorkflowForm", "WorkflowForm")
                        .WithMany("Rows")
                        .HasForeignKey("WorkflowFormId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WorkflowForm");
                });

            modelBuilder.Entity("Caspian.Engine.InnerRow", b =>
                {
                    b.HasOne("Caspian.Engine.HtmlColumn", "HtmlColumn")
                        .WithMany("InnerRows")
                        .HasForeignKey("HtmlColumnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HtmlColumn");
                });

            modelBuilder.Entity("Caspian.Engine.Model.AggregateReportGroupParameter", b =>
                {
                    b.HasOne("Caspian.Engine.Model.AggregateReportGroupParameter", "ParentParameter")
                        .WithMany("Parameters")
                        .HasForeignKey("ParentParameterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.Model.ReportGroup", "ReportGroup")
                        .WithMany("AggregateReportGroupParameters")
                        .HasForeignKey("ReportGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentParameter");

                    b.Navigation("ReportGroup");
                });

            modelBuilder.Entity("Caspian.Engine.Model.AggregateReportParameter", b =>
                {
                    b.HasOne("Caspian.Engine.Model.AggregateReportGroupParameter", "AggregateReportGroupParameter")
                        .WithMany("AggregateReportParameters")
                        .HasForeignKey("AggregateReportGroupParameterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.Report", "Report")
                        .WithMany("AggregateReportParameters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AggregateReportGroupParameter");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionDetail", b =>
                {
                    b.HasOne("Caspian.Engine.Model.ExceptionData", "ExceptionData")
                        .WithMany("Details")
                        .HasForeignKey("ExceptionDataId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("ExceptionDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExceptionData");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.HasOne("Caspian.Engine.Model.MenuCategory", "MenuCategory")
                        .WithMany("Menus")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuAccessibility", b =>
                {
                    b.HasOne("Caspian.Engine.Model.Menu", "Menu")
                        .WithMany("Accessibilities")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.Role", "Role")
                        .WithMany("MenuAccessibilities")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("Accessibilities")
                        .HasForeignKey("UserId");

                    b.Navigation("Menu");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Report", b =>
                {
                    b.HasOne("Caspian.Engine.Model.ReportGroup", "ReportGroup")
                        .WithMany("Reports")
                        .HasForeignKey("ReportGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReportGroup");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportControl", b =>
                {
                    b.HasOne("Caspian.Engine.Model.TabPanel", "TabPanel")
                        .WithMany("Controls")
                        .HasForeignKey("TabPanelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TabPanel");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportGroupParameter", b =>
                {
                    b.HasOne("Caspian.Engine.Model.ReportGroup", "ReportGroup")
                        .WithMany("ReportGroupParameters")
                        .HasForeignKey("ReportGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReportGroup");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportParam", b =>
                {
                    b.HasOne("Caspian.Engine.Model.ReportGroupParameter", "ReportGroupParameter")
                        .WithMany("ReportParams")
                        .HasForeignKey("ReportGroupParameterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.Report", "Report")
                        .WithMany("ReportParams")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Rule", "Rule")
                        .WithMany("ReportParams")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Report");

                    b.Navigation("ReportGroupParameter");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Caspian.Engine.Model.TabPanel", b =>
                {
                    b.HasOne("Caspian.Engine.Model.Report", "Report")
                        .WithMany("TabPanels")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Caspian.Engine.Model.UserMembership", b =>
                {
                    b.HasOne("Caspian.Engine.Model.Role", "Role")
                        .WithMany("Memberships")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Model.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Caspian.Engine.NodeConnector", b =>
                {
                    b.HasOne("Caspian.Engine.Activity", "Activity")
                        .WithMany("OutConnectors")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.Activity", "ToActivity")
                        .WithMany("InConnectors")
                        .HasForeignKey("ToActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("ToActivity");
                });

            modelBuilder.Entity("Caspian.Engine.TaskOperation", b =>
                {
                    b.HasOne("Caspian.Engine.Activity", "Activity")
                        .WithMany("TaskOperations")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.NodeConnector", "Connector")
                        .WithMany("TaskOperations")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("Caspian.Engine.Token", b =>
                {
                    b.HasOne("Caspian.Engine.Rule", "Rule")
                        .WithMany("Tokens")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Caspian.Engine.Rule", "RuleValue")
                        .WithMany("TokensValue")
                        .HasForeignKey("RuleIdValue")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Rule");

                    b.Navigation("RuleValue");
                });

            modelBuilder.Entity("Caspian.Engine.Workflow", b =>
                {
                    b.HasOne("Caspian.Engine.DataModel", "DataModel")
                        .WithMany("Workflows")
                        .HasForeignKey("DataModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.WorkflowGroup", "WorkflowGroup")
                        .WithMany("Workflows")
                        .HasForeignKey("WorkflowGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataModel");

                    b.Navigation("WorkflowGroup");
                });

            modelBuilder.Entity("Caspian.Engine.WorkflowForm", b =>
                {
                    b.HasOne("Caspian.Engine.DataModel", "DataModel")
                        .WithMany("WorkflowForms")
                        .HasForeignKey("DataModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Caspian.Engine.WorkflowGroup", "WorkflowGroup")
                        .WithMany("workflowForms")
                        .HasForeignKey("WorkflowGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DataModel");

                    b.Navigation("WorkflowGroup");
                });

            modelBuilder.Entity("Caspian.Engine.Activity", b =>
                {
                    b.Navigation("InConnectors");

                    b.Navigation("OutConnectors");

                    b.Navigation("TaskOperations");
                });

            modelBuilder.Entity("Caspian.Engine.BlazorControl", b =>
                {
                    b.Navigation("HtmlColumn");
                });

            modelBuilder.Entity("Caspian.Engine.DataModel", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("WorkflowForms");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Caspian.Engine.DataModelField", b =>
                {
                    b.Navigation("BlazorControls");

                    b.Navigation("DataModelOptions");
                });

            modelBuilder.Entity("Caspian.Engine.EntityType", b =>
                {
                    b.Navigation("DataModelFields");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlColumn", b =>
                {
                    b.Navigation("InnerRows");
                });

            modelBuilder.Entity("Caspian.Engine.HtmlRow", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Caspian.Engine.InnerRow", b =>
                {
                    b.Navigation("HtmlColumns");
                });

            modelBuilder.Entity("Caspian.Engine.LookupType", b =>
                {
                    b.Navigation("BlazorControls");
                });

            modelBuilder.Entity("Caspian.Engine.Model.AggregateReportGroupParameter", b =>
                {
                    b.Navigation("AggregateReportParameters");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ExceptionData", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Menu", b =>
                {
                    b.Navigation("Accessibilities");
                });

            modelBuilder.Entity("Caspian.Engine.Model.MenuCategory", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Report", b =>
                {
                    b.Navigation("AggregateReportParameters");

                    b.Navigation("ReportParams");

                    b.Navigation("TabPanels");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportGroup", b =>
                {
                    b.Navigation("AggregateReportGroupParameters");

                    b.Navigation("ReportGroupParameters");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Caspian.Engine.Model.ReportGroupParameter", b =>
                {
                    b.Navigation("ReportParams");
                });

            modelBuilder.Entity("Caspian.Engine.Model.Role", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("MenuAccessibilities");
                });

            modelBuilder.Entity("Caspian.Engine.Model.TabPanel", b =>
                {
                    b.Navigation("Controls");
                });

            modelBuilder.Entity("Caspian.Engine.Model.User", b =>
                {
                    b.Navigation("Accessibilities");

                    b.Navigation("ExceptionDetails");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Caspian.Engine.NodeConnector", b =>
                {
                    b.Navigation("TaskOperations");
                });

            modelBuilder.Entity("Caspian.Engine.Rule", b =>
                {
                    b.Navigation("DataParameters");

                    b.Navigation("ReportParams");

                    b.Navigation("Tokens");

                    b.Navigation("TokensValue");
                });

            modelBuilder.Entity("Caspian.Engine.Workflow", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Caspian.Engine.WorkflowForm", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Caspian.Engine.WorkflowGroup", b =>
                {
                    b.Navigation("DataModels");

                    b.Navigation("Workflows");

                    b.Navigation("workflowForms");
                });
#pragma warning restore 612, 618
        }
    }
}
