// <auto-generated />
using System;
using Investment.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investment.Model.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251120082353_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investment.Model.InvestmentUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentUnits", "ivm");
                });

            modelBuilder.Entity("Investment.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("LocationType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations", "ivm");
                });

            modelBuilder.Entity("Investment.Model.OrganPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrganUnitId");

                    b.ToTable("OrganPost");
                });

            modelBuilder.Entity("Investment.Model.OrganUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("ActiveStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Descript")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentOrganUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentOrganUnitId");

                    b.ToTable("OrganUnits", "ivm");
                });

            modelBuilder.Entity("Investment.Model.Location", b =>
                {
                    b.HasOne("Investment.Model.Location", "ParentLocation")
                        .WithMany("Locations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("Investment.Model.OrganPost", b =>
                {
                    b.HasOne("Investment.Model.OrganUnit", "OrganUnit")
                        .WithMany("OrganPosts")
                        .HasForeignKey("OrganUnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrganUnit");
                });

            modelBuilder.Entity("Investment.Model.OrganUnit", b =>
                {
                    b.HasOne("Investment.Model.OrganUnit", "ParentOrganUnit")
                        .WithMany("SubOrganUnits")
                        .HasForeignKey("ParentOrganUnitId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentOrganUnit");
                });

            modelBuilder.Entity("Investment.Model.Location", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("Investment.Model.OrganUnit", b =>
                {
                    b.Navigation("OrganPosts");

                    b.Navigation("SubOrganUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
