<Project Sdk="Microsoft.NET.Sdk.Razor">


	<PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <TypeScriptTarget>ES6</TypeScriptTarget>
	</PropertyGroup>


	<PropertyGroup Label="Configuration" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <TypeScriptTarget>ES6</TypeScriptTarget>
	</PropertyGroup>


	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<Compile Remove="Data\**" />
		<Compile Remove="wwwroot\Scripts\**" />
		<Content Remove="Data\**" />
		<Content Remove="wwwroot\Scripts\**" />
		<EmbeddedResource Remove="Data\**" />
		<EmbeddedResource Remove="wwwroot\Scripts\**" />
		<None Remove="Data\**" />
		<None Remove="wwwroot\Scripts\**" />
		<TypeScriptCompile Remove="wwwroot\Scripts\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Grid\Grid.rar" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.1" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
		<PackageReference Include="Microsoft.JSInterop" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Caspian.common\Caspian.Common.csproj" />
		<ProjectReference Include="..\Engine\Engine.Model\Engine.Model.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.6.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
