<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Caspian.common\Caspian.common.csproj" />
    <ProjectReference Include="..\Marketing.Model\Marketing.Model.csproj" />
  </ItemGroup>

</Project>
