<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>

		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OutputType>Library</OutputType>
		<BaseOutputPath>bin\Demo\</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Help\**" />
		<Compile Remove="Pages\GridListView\**" />
		<Compile Remove="wwwroot\Pdf\**" />
		<Content Remove="Help\**" />
		<Content Remove="Pages\GridListView\**" />
		<Content Remove="wwwroot\Pdf\**" />
		<EmbeddedResource Remove="Help\**" />
		<EmbeddedResource Remove="Pages\GridListView\**" />
		<EmbeddedResource Remove="wwwroot\Pdf\**" />
		<None Remove="Help\**" />
		<None Remove="Pages\GridListView\**" />
		<None Remove="wwwroot\Pdf\**" />
		<TypeScriptCompile Remove="Pages\GridListView\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Pages\Index.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
		<PackageReference Include="Syncfusion.EJ2.AspNet.Core" Version="29.1.33" />
		<PackageReference Include="Syncfusion.Blazor.Themes" Version="29.1.33" />
		<PackageReference Include="Syncfusion.Blazor.WordProcessor" Version="29.1.33" />
		<!--<PackageReference Include="Syncfusion.EJ2.WordEditor.AspNet.Core" Version="29.1.33" />-->
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.6.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Caspian.common\Caspian.common.csproj" />
		<ProjectReference Include="..\..\Engine\Engine.Model\Engine.Model.csproj" />
		<ProjectReference Include="..\..\Engine\Engine.Service\Engine.Service.csproj" />
		<ProjectReference Include="..\..\Engine\Engine.Web\Engine.Web.csproj" />
		<ProjectReference Include="..\..\UIComponent\UIComponent.csproj" />
		<ProjectReference Include="..\Demo.Model\Demo.Model.csproj" />
		<ProjectReference Include="..\Demo.Service\Demo.Service.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>
	<Target Name="CreateDataFolder" AfterTargets="AfterPublish">
		<MakeDir Directories="$(PublishUrl)Data" Condition="!Exists('$(PublishUrl)Data')" />
	</Target>
</Project>
