<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Caspian.common\Caspian.common.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Model\Engine.Model.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Service\Engine.Service.csproj" />
    <ProjectReference Include="..\..\Engine\Engine.Web\Engine.Web.csproj" />
    <ProjectReference Include="..\..\Finantial.Web\Finantial.Web.csproj" />
    <ProjectReference Include="..\..\UIComponent\UIComponent.csproj" />
    <ProjectReference Include="..\..\warehouse\Warehouse.Model\Warehouse.Model.csproj" />
    <ProjectReference Include="..\Procurement.Model\Procurement.Model.csproj" />
    <ProjectReference Include="..\Procurement.Service\Procurement.Service.csproj" />
  </ItemGroup>

</Project>
